---
- name: Install some packages
  become: yes
  apt:
    update_cache: yes
    autoclean: yes
    pkg:
      - unzip
      - htop
      - vim
      - nano
      - bash
      - tmux
      - screen
      - byobu
      # https://github.com/FelixKrueger/TrimGalore/issues/58
      # These appear required to prevent a crash in FastQC using Java 11 ...
      - fontconfig
      - fonts-dejavu-core
